## Libraries

In [1]:
import numpy as np
import pandas as pd
import time

## Problem 2

In [52]:
def fib_num(n=100):
    fn=[1,2]
    a,b=1,2
    while b<=n:
        a,b=b,a+b
        fn.append(b)
    return fn

def even(lst):
    return np.sum([i for i in lst if i%2==0])

In [53]:
print(even(fib_num(4e6)))

4613732


## Problem 3

In [17]:
test=13195
valid=600851475143

In [2]:
def prime_factors(n):
    primes=[]
    d=2
    while d*d <=n:
        if n%d==0:
            primes.append(float(d))
            n/=d
        else: d+=1
    if n>1: primes.append(n)
    return np.array(primes)

In [18]:
prime_factors(valid).max()

6857.0

In [6]:
pf=[prime_factors(i) for i in range(21)]

In [7]:
pf

[array([], dtype=float64),
 array([], dtype=float64),
 array([2]),
 array([3]),
 array([2., 2.]),
 array([5]),
 array([2., 3.]),
 array([7]),
 array([2., 2., 2.]),
 array([3., 3.]),
 array([2., 5.]),
 array([11]),
 array([2., 2., 3.]),
 array([13]),
 array([2., 7.]),
 array([3., 5.]),
 array([2., 2., 2., 2.]),
 array([17]),
 array([2., 3., 3.]),
 array([19]),
 array([2., 2., 5.])]

## Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.


In [75]:
e=999*999
s=100*100

In [76]:
def find_palindromes(s,e):
    palindromes=[]
    for i in range(s,e+1):
        if str(i)==''.join(reversed(list(str(i)))):
            palindromes.append(i)
    return np.array(palindromes)

In [77]:
def largest_p(pals, div_dig):
    pals_d={}
    for p in reversed(pals):
        pals_d[p]=[i for i in range(int(''.join(['1']+(['0']*(div_dig-1)))),int(''.join(['9']*div_dig)))
                  if p%i==0 and len(str(int(p/i)))==div_dig]
    return pals_d

In [78]:
p=find_palindromes(s,e)

In [79]:
pd=largest_p(p,3)

In [80]:
pals=np.array([i for i in pd if len(pd[i])>0])

In [81]:
pals.max()

906609

## Problem 5


2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?


In [84]:
def divisible_by(n):
    t0=time.time()
    divs=np.array([i for i in range(1,n+1)])
    cnt,a,n=1,divs[-1]*divs[-2],0
    while cnt!=0:
        n+=a
        cnt=(n%divs).sum()
    #print('processed in {:.2f} secs'.format(time.time()-t0))
    return n,time.time()-t0

In [28]:
divisible_by(20)

processed in 38.32 secs


232792560

In [46]:
divisible_by(20)

processed in 2.32 secs


232792560

In [63]:
divisible_by(20)

processed in 0.15 secs


232792560

In [90]:
divisible_by(20)

(232792560, 2.114284038543701)

In [83]:
2520/(10*9*8*7)

0.5

In [92]:
time_test=[{'int':i,'divisible':divisible_by(i)[0],'time':divisible_by(i)[1]} for i in range(7,21)]
tt_df=pd.DataFrame(time_test)
tt_df

divisible  int      time
0         420    7  0.000205
1         840    8  0.000078
2        2520    9  0.000171
3        2520   10  0.000138
4       27720   11  0.001619
5       27720   12  0.001234
6      360360   13  0.013610
7      360360   14  0.013104
8      360360   15  0.010906
9      720720   16  0.012241
10   12252240   17  0.142656
11   12252240   18  0.189711
12  232792560   19  2.180730
13  232792560   20  2.075209

## Problem 6


The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)^2 = 55^2 = 3025

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.


In [3]:
n=100
a=np.array([i for i in range(1,n+1)])
(((a**2).sum()-(a.sum())**2)**2)**(1/2)

25164150.0

## Problem 7

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?


In [25]:
def split_in_digits(n):
    return [int(i) for i in list(str(n))]

In [32]:
def end_in_five(n):
    if str(n)[-1]=='5': return True
    else: return False

In [44]:
def is_prime(n):
    pn=False
    if n in [2,3,5]: return True
    elif n%2==0: return False
    elif sum(split_in_digits(n))%3==0: return False
    elif end_in_five(n)==True: return False
    elif n<2: return False
    return True

In [41]:
def n_prime(n):
    pn=[]
    x=2
    while len(pn)<n:
        if is_prime(x):
            pn.append(x)
        x+=1
    return np.array(pn)    

In [43]:
n_prime(10001).max()

37493

## Problem 8

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?


In [2]:
txt="""73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450"""

In [14]:
n=13

In [15]:
options_list=[]
for i in range(len(txt)):
    options_list.append((''.join([txt[i:i+n]])))

In [16]:
len(options_list)

1000

In [17]:
finals=[]
for s in options_list:
    s_np=np.array([int(i) for i in list(s)])
    finals.append([s,s_np,s_np.prod()])

In [18]:
df=pd.DataFrame(finals)
df.sort_values(by=2, ascending=False).iloc[0]

0                              5576689664895
1    [5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5]
2                                23514624000
Name: 197, dtype: object

## Problem 9

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a2 + b2 = c2

For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

a+b+c=1000

a<b<c

a^2+b^2=c^2

a^2+b^2-c^2=0

c=1000-a-b

c=(a^2+b^2)^0.5




1000-a-b=(a^2+b^2)^0.5

(1000-a-b)(1000-a-b)=a^2+b^2

1000000-1000a-1000b-1000a+a^2+ab-1000b+ab+b^2=a^2+b^2

1000000-2000a-2000b+a^2+2ab+b^2 = a^2+b^2

1000000-2000a-2000b+2ab=0

500000=1000a+1000b-ab

500 = a+b-ab/1000



In [45]:
a, b = 3, 4

In [53]:
a**2+b**2

25

1000000

## Problem 10

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.


## Problem 11

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

See picture

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

## Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?


## Problem 13
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

In [1]:
n = 
"""
37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690
"""

SyntaxError: invalid syntax (<ipython-input-1-573931dddbf1>, line 1)