## Libraries

In [1]:
import numpy as np
import pandas as pd

## Problem 2

In [52]:
def fib_num(n=100):
    fn=[1,2]
    a,b=1,2
    while b<=n:
        a,b=b,a+b
        fn.append(b)
    return fn

def even(lst):
    return np.sum([i for i in lst if i%2==0])

In [53]:
print(even(fib_num(4e6)))

4613732


## Problem 3

In [17]:
test=13195
valid=600851475143

In [2]:
def prime_factors(n):
    primes=[]
    d=2
    while d*d <=n:
        if n%d==0:
            primes.append(float(d))
            n/=d
        else: d+=1
    if n>1: primes.append(n)
    return np.array(primes)

In [18]:
prime_factors(valid).max()

6857.0

In [6]:
pf=[prime_factors(i) for i in range(21)]

In [7]:
pf

[array([], dtype=float64),
 array([], dtype=float64),
 array([2]),
 array([3]),
 array([2., 2.]),
 array([5]),
 array([2., 3.]),
 array([7]),
 array([2., 2., 2.]),
 array([3., 3.]),
 array([2., 5.]),
 array([11]),
 array([2., 2., 3.]),
 array([13]),
 array([2., 7.]),
 array([3., 5.]),
 array([2., 2., 2., 2.]),
 array([17]),
 array([2., 3., 3.]),
 array([19]),
 array([2., 2., 5.])]

## Problem 4

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.


In [75]:
e=999*999
s=100*100

In [76]:
def find_palindromes(s,e):
    palindromes=[]
    for i in range(s,e+1):
        if str(i)==''.join(reversed(list(str(i)))):
            palindromes.append(i)
    return np.array(palindromes)

In [77]:
def largest_p(pals, div_dig):
    pals_d={}
    for p in reversed(pals):
        pals_d[p]=[i for i in range(int(''.join(['1']+(['0']*(div_dig-1)))),int(''.join(['9']*div_dig)))
                  if p%i==0 and len(str(int(p/i)))==div_dig]
    return pals_d

In [78]:
p=find_palindromes(s,e)

In [79]:
pd=largest_p(p,3)

In [80]:
pals=np.array([i for i in pd if len(pd[i])>0])

In [81]:
pals.max()

906609

## Problem 5


2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?


## Problem 8

In [2]:
txt="""73167176531330624919225119674426574742355349194934\
96983520312774506326239578318016984801869478851843\
85861560789112949495459501737958331952853208805511\
12540698747158523863050715693290963295227443043557\
66896648950445244523161731856403098711121722383113\
62229893423380308135336276614282806444486645238749\
30358907296290491560440772390713810515859307960866\
70172427121883998797908792274921901699720888093776\
65727333001053367881220235421809751254540594752243\
52584907711670556013604839586446706324415722155397\
53697817977846174064955149290862569321978468622482\
83972241375657056057490261407972968652414535100474\
82166370484403199890008895243450658541227588666881\
16427171479924442928230863465674813919123162824586\
17866458359124566529476545682848912883142607690042\
24219022671055626321111109370544217506941658960408\
07198403850962455444362981230987879927244284909188\
84580156166097919133875499200524063689912560717606\
05886116467109405077541002256983155200055935729725\
71636269561882670428252483600823257530420752963450"""

In [14]:
n=13

In [15]:
options_list=[]
for i in range(len(txt)):
    options_list.append((''.join([txt[i:i+n]])))

In [16]:
len(options_list)

1000

In [17]:
finals=[]
for s in options_list:
    s_np=np.array([int(i) for i in list(s)])
    finals.append([s,s_np,s_np.prod()])

In [18]:
df=pd.DataFrame(finals)
df.sort_values(by=2, ascending=False).iloc[0]

0                              5576689664895
1    [5, 5, 7, 6, 6, 8, 9, 6, 6, 4, 8, 9, 5]
2                                23514624000
Name: 197, dtype: object